name: Build & Tests

on:
  push:
    branches: [ 2.x, master ]
  pull_request:
    branches: [ 2.x, master ]

jobs:
  build:
    strategy:
      matrix:
        xcode: ['/Applications/Xcode_12.2.app/Contents/Developer', '/Applications/Xcode_11.7.app/Contents/Developer']
    name: Build and Test Sparkle
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Unit Tests
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
        run: |
          xcodebuild build-for-testing -project Sparkle.xcodeproj -scheme Distribution -enableCodeCoverage YES -derivedDataPath build
      - name: Run Unit Tests
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
        run: |
          xcodebuild test-without-building -project Sparkle.xcodeproj -scheme Distribution -enableCodeCoverage YES -derivedDataPath build
      - name: Build UI Tests
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
        run: |
          xcodebuild build-for-testing -project Sparkle.xcodeproj -scheme UITests -configuration Debug -derivedDataPath build
      - name: Run UI Tests
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
        run: |
          xcodebuild test-without-building -project Sparkle.xcodeproj -scheme UITests -configuration Debug -derivedDataPath build
      - name: Archive Test Results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: build/Logs
